<h4>Reembolsos y devoluciones</h4>
<div class="g nine-twelfths customer_service"><h2>Política de cancelación</h2><strong>Derecho a cancelar</strong><p>Tiene derecho a cancelar este contrato en un plazo de catorce días sin indicar las razones de ello. El periodo de cancelación dura catorce días desde la fecha en la que usted o un tercero que usted designe, que no sea el transportista, tome posesión de la mercancía.</p><p>A fin de ejercer su derecho de cancelación, deberá notificarnos (Decora tu Casa / Nordic eTrade AB, Fraktflygargatan 18, 128 21 Skarpnäck, atencionalcliente@decoratucasa.com.ar, teléfono: +34-518888336) su decisión de cancelar este contrato por medio de una declaración explícita (p. ej., una carta enviada por correo postal, un fax o un correo electrónico). Puede, aunque no es obligatorio, utilizar el siguiente formulario de ejemplo de cancelación.
</p><p>El envío a tiempo de la notificación en la que declara ejercer su derecho de cancelación es suficiente para que se respete el periodo de cancelación.</p><h2>Consecuencia de la cancelación</h2><p>Si cancela este contrato, deberemos reembolsarle todos sus pagos recibidos, incluyendo los gastos de entrega (a excepción de los gastos adicionales derivados de su decisión de utilizar un tipo de entrega diferente al estándar más económico que le ofrecemos), sin aplazamientos y no después de los catorce días a partir de la fecha en que recibamos su notificación de cancelación del presente contrato. A fin de facilitar el reembolso, utilizamos los mismos métodos de pago que usted utilizó en la transacción original, a menos que expresamente acordemos con usted otro método. En ningún caso se le cargarán los suplementos derivados de este reembolso.
Podemos rechazar realizar el reembolso hasta que hayamos recibido las mercancías devueltas o hasta que nos pueda dar prueba de que ha devuelto la mercancía, lo que antes ocurra. <br><br>
Cualquier gasto derivado de la colocación del papel pintado no se reembolsará en caso de reclamación. Por lo tanto, es importante que compruebe el estado del producto antes de colocarlo. Si ha separado los paneles para inspeccionar el papel pintado más de cerca, esto no implicará una reducción de su valor. Podrá devolver el papel pintado.</p><p>
Deberá entregar o enviar de vuelta la mercancía inmediatamente y, en cualquier caso, antes de catorce días desde la fecha en que nos notifique la cancelación de este contrato. El envío a tiempo de la mercancía antes de que expiren los catorce días es suficiente para respetar el periodo de cancelación.
Usted asumirá los gastos directos de la devolución de la mercancía. Los artículos encargados por error o dañados se devolverán y sustituirán sin coste adicional. <br><br>

Usted abonará cualquier pérdida de valor de la mercancía únicamente si esta se deriva de una manipulación innecesaria de la mercancía durante la inspección de calidad, características y función de la misma.
</p><strong>Formulario de ejemplo de cancelación</strong><br><p>(Si desea cancelar el contrato, complete este formulario y envíenoslo).</p><p>- A Decora tu Casa / Nordic eTrade AB, Fraktflygargatan 18, 128 21 Skarpnäck, atencionalcliente@decoratucasa.com.ar, fax: +46 (0)8-648 69 50</p><p>- Por la presente yo/nosotros (*) cancelo/cancelamos el contrato firmado por mi/nosotros (*) para la adquisición de la siguiente mercancía (*)/el suministro del siguiente servicio (*)</p><p>- Pedido el (*)/recibidos el (*),</p><p>- Nombre del/los cliente/es,</p><p>- Dirección del/los cliente/es,</p><p>- Firma del/los cliente/es (solo para la copia en papel de la notificación)</p><p>- Fecha</p><p>(*) Borrar según convenga.</p></div>
