<h4>Términos y condiciones de compra</h4>
<div class="g nine-twelfths customer_service editable"><p></p><p>Comprar con Decora tu Casa es fácil y seguro. Los pedidos confirmados en días laborables se entregarán al día siguiente como muy tarde. El transporte siempre es gratuito. Todos los precios incluyen el IVA. A continuación puede consultar las Condiciones Generales de la Contratación al completo.</p><p>La presentación de los productos de nuestra tienda online no es una oferta legalmente vinculante sino un catálogo online no vinculante. Haciendo clic en el botón "Confirmar pedido" está confirmando un pedido vinculante para la mercancía contenida en el carrito de la compra. La confirmación de recepción de su pedido se realiza mediante la aceptación de su pedido inmediatamente después de enviar un correo electrónico automático. El contrato de venta entra en vigor con este correo electrónico de confirmación.<br><br>
Guardaremos el texto del contrato y le enviaremos los detalles del pedido por correo electrónico. Puede consultar las Condiciones Comerciales en cualquier momento<a target="_blank" href="<? echo base_url(); ?>customer-service/terms-and-conditions"> aquí.</a> Los detalles de su pedido ya no están disponibles online por motivos de seguridad. </p><p></p><h2>Plazos de entrega y gastos de envío</h2><p>Todos los pedidos se entregan al siguiente día laborable como muy tarde.
Para asuntos urgentes, póngase en contacto con nosotros a través de: <a href="atencionalcliente@decoratucasa.com.ar.">atencionalcliente@decoratucasa.com.ar.</a><br><br>Transporte realizado con DB Schenker. Una vez que hayamos enviado su pedido, recibirá un correo electrónico con la confirmación de la entrega. Este correo electrónico de confirmación incluye una opción para el seguimiento del paquete. Está en su derecho a cancelar su compra sin gastos adicionales en caso de que se produzca un retraso en la producción.</p><p><strong>Plazos de entrega: 4 - 5 días laborables</strong></p><p>

Existen ciertas excepciones en caso de retrasos provocados por la compañía de transporte. <br><br>
¡Puede realizar el seguimiento de su envío a través de la<a href="http://www.logistics.dbschenker.co.uk/log-uk-en/start/productsservices/land/onlineservices/Tracking/tracking.html"> página de seguimiento de DB Schenker aquí!</a><br><br><strong>Envíos siempre gratis</strong></p><h2>Reembolsos y devoluciones</h2><h2>Política de cancelación</h2><strong>Derecho a cancelar</strong><p>Tiene derecho a cancelar este contrato en un plazo de catorce días sin indicar las razones de ello. El periodo de cancelación dura catorce días desde la fecha en la que usted o un tercero que usted designe, que no sea el transportista, tome posesión de la mercancía.</p><p>A fin de ejercer su derecho de cancelación, deberá notificarnos (Decora tu Casa / Nordic eTrade AB, Fraktflygargatan 18, 128 21 Skarpnäck, atencionalcliente@decoratucasa.com.ar, teléfono: +34-518888336) su decisión de cancelar este contrato por medio de una declaración explícita (p. ej., una carta enviada por correo postal, un fax o un correo electrónico). Puede, aunque no es obligatorio, utilizar el siguiente formulario de ejemplo de cancelación.
</p><p>El envío a tiempo de la notificación en la que declara ejercer su derecho de cancelación es suficiente para que se respete el periodo de cancelación.</p><h2>Consecuencia de la cancelación</h2><p>Si cancela este contrato, deberemos reembolsarle todos sus pagos recibidos, incluyendo los gastos de entrega (a excepción de los gastos adicionales derivados de su decisión de utilizar un tipo de entrega diferente al estándar más económico que le ofrecemos), sin aplazamientos y no después de los catorce días a partir de la fecha en que recibamos su notificación de cancelación del presente contrato. A fin de facilitar el reembolso, utilizamos los mismos métodos de pago que usted utilizó en la transacción original, a menos que expresamente acordemos con usted otro método. En ningún caso se le cargarán los suplementos derivados de este reembolso.
Podemos rechazar realizar el reembolso hasta que hayamos recibido las mercancías devueltas o hasta que nos pueda dar prueba de que ha devuelto la mercancía, lo que antes ocurra. <br><br>
Cualquier gasto derivado de la colocación del papel pintado no se reembolsará en caso de reclamación. Por lo tanto, es importante que compruebe el estado del producto antes de colocarlo. Si ha separado los paneles para inspeccionar el papel pintado más de cerca, esto no implicará una reducción de su valor. Podrá devolver el papel pintado.</p><p>
Deberá entregar o enviar de vuelta la mercancía inmediatamente y, en cualquier caso, antes de catorce días desde la fecha en que nos notifique la cancelación de este contrato. El envío a tiempo de la mercancía antes de que expiren los catorce días es suficiente para respetar el periodo de cancelación.
Usted asumirá los gastos directos de la devolución de la mercancía. Los artículos encargados por error o dañados se devolverán y sustituirán sin coste adicional. <br><br>

Usted abonará cualquier pérdida de valor de la mercancía únicamente si esta se deriva de una manipulación innecesaria de la mercancía durante la inspección de calidad, características y función de la misma.
</p><strong>Formulario de ejemplo de cancelación</strong><br><p>(Si desea cancelar el contrato, complete este formulario y envíenoslo).</p><p>- A Decora tu Casa / Nordic eTrade AB, Fraktflygargatan 18, 128 21 Skarpnäck, atencionalcliente@decoratucasa.com.ar, fax: +46 (0)8-648 69 50</p><p>- Por la presente yo/nosotros (*) cancelo/cancelamos el contrato firmado por mi/nosotros (*) para la adquisición de la siguiente mercancía (*)/el suministro del siguiente servicio (*)</p><p>- Pedido el (*)/recibidos el (*),</p><p>- Nombre del/los cliente/es,</p><p>- Dirección del/los cliente/es,</p><p>- Firma del/los cliente/es (solo para la copia en papel de la notificación)</p><p>- Fecha</p><p>(*) Borrar según convenga.</p><h2>Opciones de pago</h2><li><span>1) Pago con tarjeta</span><p><img alt="Visa, MasterCard" src="/img/imgSpecial/creditCards_payoptions2.gif"></p> Actualmente, aceptamos el pago con VISA y MasterCard. No aplicamos recargos por tarjeta de crédito. <br><br>
El pago se carga en su tarjeta de crédito cuando se realiza el pedido.<br><br></li><li><span>2) Paypal</span> - Pague con su cuenta de PayPal</li><li><span>3) Sofort Banking</span> - Pago directo desde su cuenta Sofort</li><h2>Política de confidencialidad</h2><h2>Declaración de protección de datos</h2><p>
Le agradecemos su interés en nuestro sitio web. La protección de su privacidad es importante para nosotros. A continuación, se ofrece información detallada sobre cómo gestionamos sus datos.
</p><h2>Recolección y uso de datos para el procesamiento de pedidos </h2><p>

Recogemos sus datos personales si usted nos los proporciona voluntariamente cuando confirma un pedido o se pone en contacto con nosotros (p. ej., a través del formulario de contacto o por correo electrónico). Los datos que recogemos se pueden consultar en los pertinentes formularios de inscripción. Utilizaremos los datos que nos haya facilitado para procesar sus pedidos y tratar sus consultas. Cuando se haya finalizado el pedido y realizado el pago completo, se bloquearán sus datos de acuerdo con las leyes fiscales y comerciales y se eliminarán cuando expire el plazo, siempre que usted no acceda expresamente a un uso más extenso de sus datos o que nos reservemos el derecho, según lo permitido por ley, para utilizar los datos de manera más extensa a la indicada a continuación.
</p><h2>Envío de datos para completar el pedido</h2><p>
A fin de completar el pedido, facilitamos sus a la empresa de correo designada para entregar su pedido, teniendo en cuenta que esto es necesario para la entrega de las mercancías encargadas. Para procesar los pagos, facilitamos los datos pertinentes a la entidad bancaria autorizada y, cuando resulte necesario, al proveedor de servicios de pago autorizado o al servicio de pago que usted haya seleccionado durante el proceso del pedido.
</p><h2>Uso de los datos al suscribirse en el boletín electrónico</h2><p>
Si se da de alta en nuestro boletín, utilizaremos para ello los datos pertinentes o los que nos haya facilitado de manera independiente para enviarle un boletín electrónico de manera periódica. Puede dar de baja su suscripción al boletín en cualquier momento poniéndose en contacto con nosotros tal y como se describe más abajo o mediante el enlace que incluye el boletín.
</p><h2>Uso de las cookies</h2><p>
Para mejorar la experiencia del usuario de nuestro sitio web y posibilitar el uso de ciertas funciones, utilizamos las llamadas cookies en varias páginas. Se trata de pequeños archivos de texto que se almacenan en su dispositivo. Algunas de las cookies se borran cuando finaliza su sesión en el navegador, p. ej., cuando cierra su navegador (las llamadas cookies de sesión). Otras cookies permanecen en su dispositivo y nos permiten reconocer su navegador la próxima vez que nos visite (cookies persistentes). También puede configurar su navegador para que le avise antes de que reciba una cookie de manera que pueda decidir cuándo y si desea aceptar la cookie o aceptar las cookies en ciertos casos o excluirlas de manera general. Si no se acepta una cookie, la funcionalidad de nuestro sitio web puede verse restringida.
</p><h2>Uso de Google Analytics para análisis web</h2><p>
Este sitio web utiliza Google Analytics, un servicio de análisis web de Google Inc. (www.google.co.uk). Google Analytics utiliza las llamadas "cookies", p. ej. archivos de texto que se guardan en su ordenador y permiten un análisis de cómo utiliza el sitio web. La información generada por la cookie sobre su uso de este sitio web generalmente se transfiere y guarda en un servidor ubicado en EE.UU. En caso de que se active la anonimización de IP en este sitio web, Google abreviará previamente su dirección IP dentro de los Estados miembros de la Unión Europea o en otros Estados partes del Acuerdo sobre el Espacio Económico Europeo. Solo en casos excepcionales se enviará la IP completa a un servidor de Google en los EE.UU., para ser abreviada allí posteriormente. La anonimización de IP está activada en este sitio web. En nombre del operador de este sitio web, Google utilizará esta información para analizar su uso del sitio web, realizar informes relacionados con la actividad del sitio web para el operario del sitio web y para proporcionar otros servicios relacionados con el uso del sitio web y de internet. La dirección IP enviada por su navegador como parte de Google Analytics no se asocia con otros datos que tenga Google. Puede rechazar el uso de cookies seleccionando los ajustes adecuados de su navegador, sin embargo, tenga en cuenta que en caso de hacerlo podría no ser posible el uso de todas las funcionalidades de este sitio web.<br><br>
También puede detener el envío y procesamiento que realiza Google de la recogida de datos generada por la cookie y relacionada con su uso del sitio web (incluida su dirección IP) descargándose e instalando el plugin de navegador que encontrará en el siguiente enlace: <a href="http://tools.google.com/dlpage/gaoptout?hl=de" target="_blank">http://tools.google.com/dlpage/gaoptout?hl=de</a><br><br>
En lugar del plugin de navegador puede hacer clic en
<a href="nojavascript...gaOptout()" target="_blank">este enlace</a> para que Google Analytics deje de recoger datos de este sitio web en el futuro. En ese caso, se instalará una cookie de rechazo en su dispositivo. Si borra las cookies, deberá volver a hacer clic en el enlace.
</p><h2>Uso de ClickTale y Optimizely para análisis web </h2><p>
Los datos son recogidos y guardados en este sitio web utilizando tecnologías de ClickTale Ltd y Optimizely (http://www.clicktale.com/, https://www.optimizely.com/). Los datos se utilizan para crear perfiles de usuario mediante el uso de pseudónimos. Estos perfiles de usuario se utilizan para analizar el comportamiento del visitante, que a su vez se evalúa para mejorar y personalizar nuestros servicios según las necesidades del cliente. Las cookies también se pueden utilizar aquí. Son pequeños archivos de textos que se almacenan de manera local en el dispositivo del visitante del sitio web de manera que el visitante es reconocido cuando vuelve a visitar el sitio web. Los perfiles de usuario con pseudónimo no se combinan con datos personales pertenecientes al dueño del pseudónimo a menos que este haya accedido a ello de manera independiente y expresa.<br><br>

Puede negarse a la recolección y almacenamiento de sus datos en cualquier momento y con efectos a futuro.
</p><h2>Uso de plugins de Facebook </h2><p>
Los llamados plugins sociales (“plugins”) son utilizados en nuestro sitio web por la red social Facebook, controlado por Facebook Inc., 1601 S. California Ave, Palo Alto, CA 94304, USA (“Facebook”). Los plugins son reconocibles por el logotipo de Facebook o la adición de "Plugin social de Facebook" o "Facebook plugin social". Aquí encontrará una visión general de los plugins de Facebook y de su aspecto: <a href="http://developers.facebook.com/plugins" target="_blank">http://developers.facebook.com/plugins</a><br><br>
Si solicita una página en nuestro sitio web que contenga dicho plugin, su navegador construirá una conexión directa con los servidores de Facebook. Facebook proporciona directamente el contenido del plugin a su navegador y lo entrega en el sitio web. Al integrar el plugin, Facebook recibe la información que su navegador ha solicitado a la página de nuestro sitio web, incluso si no tiene cuenta de Facebook o si no tiene sesión abierta en estos momentos en Facebook. Esta información (incluida su dirección IP) la envía directamente su navegador al servidor de Facebook en los EE.UU. donde se almacena.
<br><br>
Si tiene sesión iniciada en Facebook, Facebook podrá asignar la visita directamente a su cuenta de Facebook. Si interactúa con el plugin, utilizando el botón "Me gusta", por ejemplo, o publicando un comentario, la información se enviará directamente al servidor de Facebook donde se almacenará. La información también se publicará en su perfil de Facebook y sus amigos de Facebook podrán verla.
<br><br>
Para obtener más información sobre el objetivo y extensión de la recolección de datos y su posterior procesamiento y uso de los datos por parte de Facebook, así como sobre sus derechos en lo relativo a esta cuestión y las opciones de bloqueo para la protección de su privacidad, consulte la información de Facebook sobre la protección de datos: <a href="http://www.facebook.com/policy.php" target="_blank">http://www.facebook.com/policy.php</a><br><br>
Si no desea que Facebook vincule los datos recogidos sobre usted a través de nuestro sitio web con su cuenta de Facebook, deberá cerrar sesión en Facebook antes de acceder a nuestro sitio web. También puede bloquear completamente los plugins de Facebook instalando un complemento en su navegador como, por ejemplo, "Facebook Blocker" (<a href="http://webgraph.com/resources/facebookblocker/" target="_blank">http://webgraph.com/resources/facebookblocker/</a>) o el bloqueador de script “NoScript” (<a href="http://noscript.net/" target="_blank">http://noscript.net/</a>).
</p><h2>Uso de los plugins de Twitter (p. ej., botón "Twitter")</h2><p>
El servicio de microblogging Twitter, gestionado por Twitter Inc., 1355 Market St, Suite 900, San Francisco, CA 94103, EE.UU. ("Twitter") utiliza plugins sociales ("plugins") en nuestro sitio web. Los plugins se pueden reconocer por el logotipo de Twitter, p. ej., en forma del pájaro azul "Twitter". Aquí encontrará una visión general de los plugins de Twitter y de su aspecto: <a href="https://twitter.com/about/resources/buttons" target="_blank">https://twitter.com/about/resources/buttons</a><br><br>
Si solicita una página en nuestro sitio web que contenga dicho plugin, su navegador construirá una conexión directa con los servidores de Twitter. Twitter proporciona directamente el contenido del plugin a su navegador y lo entrega en el sitio web. Al integrar el plugin, Twitter recibe la información que su navegador ha solicitado a la página de nuestro sitio web, incluso si no tiene cuenta de Twitter o si no tiene sesión abierta en estos momentos en Twitter. Esta información (incluida su dirección IP) la envía directamente su navegador al servidor de Twitter en los EE.UU. donde se almacena.
<br><br>
Si tiene sesión abierta en Twitter, Twitter podrá asignar la visita directamente en su cuenta de Twitter. Si interacciona con el plugin, utilizando el "botón Twitter", por ejemplo, la información se enviará directamente a un servidor de Twitter donde se almacenará. La información también se publicará en su cuenta de Twitter y sus contactos podrán verla.<br><br>
Para obtener más información sobre el objetivo y extensión de la recolección de datos y su posterior procesamiento y uso de los datos por parte de Twitter, así como sobre sus derechos en lo relativo a esta cuestión y las opciones de bloqueo para la protección de su privacidad, consulte la información de Twitter sobre la protección de datos: <a href="https://twitter.com/privacy" target="_blank">https://twitter.com/privacy</a> Si no desea que Twitter vincule los datos recogidos sobre usted a través de nuestro sitio web con su cuenta de Twitter, deberá cerrar sesión en Twitter antes de acceder a nuestro sitio web. También puede bloquear los plugins de Twitter con complementos instalados en su navegador, p. ej. con el bloqueador de script “NoScript” (<a href="http://noscript.net/" target="_blank">http://noscript.net/</a>).
</p><h2>Uso de Google+ plugins (p. ej., botón “+1”) </h2><p>
La red social Google+, administrada por Google Inc., 1600 Amphitheatre Parkway, Mountain View, CA 94043, EE.UU. (“Google”), utiliza los llamados plugins sociales (“plugins”) en nuestro sitio web. Los plugins pueden reconocerse por ejemplo por botones con el signo "+1" con fondo blanco o de color. Aquí encontrará una visión general de los plugins de Google y de su aspecto: https://developers.google.com/+/plugins
<br><br>
Si solicita una página en nuestro sitio web que contenga dicho plugin, su navegador construirá una conexión directa con los servidores de Google. Google proporciona directamente el contenido del plugin a su navegador y lo entrega en el sitio web. Al integrar el plugin, Google recibe la información que su navegador ha solicitado a la página de nuestro sitio web, incluso si no tiene cuenta de Google o si no tiene sesión abierta en estos momentos en Google+. Esta información (incluida su dirección IP) la envía directamente su navegador al servidor de Google en los EE.UU. donde se almacena.
<br><br>
Si tiene iniciada su sesión en Google+, Google podrá asignar la visita directamente a su cuenta de Google+. Si interacciona con el plugin, utilizando el botón "+1", por ejemplo, la información se enviará directamente a un servidor de Google donde se almacenará. La información también se publicará en Google+ y se mostrará a sus contactos.
<br><br>
Para obtener más información sobre el objetivo y extensión de la recolección de datos y su posterior procesamiento y uso de los datos por parte de Google, así como sobre sus derechos en lo relativo a esta cuestión y las opciones de bloqueo para la protección de su privacidad, consulte la información de Google sobre la protección de datos: <a href="http://www.google.com/intl/de/+/policy/+1button.html" target="_blank">http://www.google.com/intl/de/+/policy/+1button.html</a><br><br>
Si no desea que Google vincule los datos recogidos sobre usted a través de nuestro sitio web con su cuenta de Google+, deberá cerrar sesión en Google+ antes de acceder a nuestro sitio web. También puede bloquear los plugins de Google con complementos instalados en su navegador, p. ej., el bloqueador de script “NoScript” (<a href="http://noscript.net/" target="_blank">http://noscript.net/</a>).
</p><h2>Recordatorio de evaluación por Trustpilot</h2><p>
Proporcionado durante o después de su pedido, nos habrá dado su consentimiento expreso habilitando la casilla correspondiente o haciendo clic en el botón facilitado, enviaremos su dirección de correo electrónico a Trustpilot, Inc., https://www.trustpilot.com (https://www.trustpilot.com), quien le recordará mediante correo electrónico que envíe una evaluación de su pedido. Este consentimiento se puede revocar en cualquier momento notificándolo al contacto que se indica a continuación o a Trustpilot directamente.
</p><h2>Derecho a información y punto de contacto</h2><p>
Tiene derecho a recibir información sin cargo adicional sobre los datos que almacenemos sobre usted, así como a la corrección, bloqueo o eliminación de dichos datos. Para preguntas relacionadas con la recogida, el procesamiento o el uso de su información personal, la divulgación, corrección, bloqueo o eliminación de datos, y la revocación de consentimientos dados o el rechazo a un determinado uso de los datos, póngase en contacto con nosotros directamente mediante los datos de contacto indicados en nuestro aviso legal.
</p><h2> Aviso de protección de datos de Klarna</h2><br><br><p>
Uso de datos personales cuando se selecciona Klarna como método de pago. 
Si selecciona los servicios de pago de Klarna Invoice y Klarna Hire-Purchase como método de pago, nos estará dando su consentimiento para que recojamos y enviemos a Klarna los siguientes datos personales necesarios, como nombre y apellidos, dirección, fecha de nacimiento, sexo, dirección de correo electrónico, dirección IP y número de teléfono, a fin de procesar las compras a cuenta y para realizar una verificación de identidad y crédito así como de los datos necesarios para procesar las compras a cuenta relacionada con el pedido, como el número de artículos, el número del artículo, el montante de la factura y los porcentajes fiscales. <br><br>La transferencia de estos datos se realiza para posibilitar que Klarna genere una factura del modo que usted elija, de manera que se pueda procesar su compra y realizar una verificación de su identidad y crédito. Por lo tanto, de acuerdo con la Ley de protección de datos del gobierno federal alemán, Klarna tiene un interés justificado en la transferencia de los datos personales del comprador y los solicita a fin de obtener información de 
las agencias de crédito para realizar una verificación de identidad y crédito. En Alemania, estas serán las</p><p>

agencias de crédito:

</p><ul><li>Schufa Holding AG, Kormoranweg 5, 65203 Wiesbaden</li><li>Bürgel Wirtschaftsinformationen GmbH &amp; Co. KG, Postfach 5001 66, 22701 Hamburg</li><li>Creditreform Bremen Seddig KG, Contrescarpe 17, 28203 Bremen</li><li>Infoscore Consumer Data GmbH, Rheinstraße 99, 76532 Baden-Baden</li></ul><p>
Cuando decide establecer, efectuar o finalizar la relación contractual, paralelamente de una comprobación de dirección, Klarna también recoge y utiliza información del historial de compras previas del comprador así como de los valores de probabilidad relacionados con el comportamiento de pago en el futuro El cálculo que realiza Klarna de estos valores se lleva a cabo mediante un procedimiento estadístico científicamente reconocido. Klarna también utiliza sus datos de dirección, entre otras cosas, para este proceso. Si el cálculo muestra que no se puede establecer su solvencia, Klarna le informará de ello inmediatamente.
</p><p>
Rechazo a que Klarna utilice sus datos personales
</p><p>
1. Puede revocar su consentimiento al uso que Klarna haga de sus datos personales en cualquier momento. Sin embargo, Klarna seguirá teniendo derecho a procesar, utilizar y transmitir sus datos personales, siempre que esto sea necesario para el procesamiento contractual de pagos a través de los servicios de Klarna, que esté permitido por ley o que haya sido requerido por una autoridad judicial.<br><br>
2. Por supuesto, podrá obtener información acerca de los datos personales que almacene Klarna en cualquier momento. La Ley de protección de datos del gobierno federal alemán le garantiza este derecho. Si usted, el comprador, desea ejercer este derecho o si desea notificar a Klarna cualquier cambio en los datos almacenados, puede ponerse en contacto con datenschutz@klarna.de.</p></div>
